### ISSUE TITLE
Linux project corruption

### ISSUE THREAD

**Issue by AdalynBlack** [theepicsnail/Marker#10]
When using this on Linux, it creates a directory under the name "Snail\\Marker3.0\\Generated\\". In Windows, I assume this is translated to three separate directories, but on Linux, this is not so. This creates some slight issues trying to set it up, but the issue is not immediately obvious. After attempting to reload the project, when Unity finds this directory containing a \\ in the name, it crashes, effectively corrupting the project unless one realizes this issue and corrects it manually. It took me nearly a month to realize this was the issue, and I haven't been able to work on my avatar since. If a correction could be made to prevent this from happening in the future, I and any other Linux users would be very greatful.

**Comment by theepicsnail** [comment]
Fixed in https://github.com/theepicsnail/Marker/commit/99600addd8c86470a47db1aa6e2aff564ca5ddb6
