### ISSUE TITLE
Smooth Normals on Marker

### ISSUE THREAD

**Issue by owlboy** [theepicsnail/Marker#2]
Hello,

I still don't know the proper ways to checkout code and do all the fancy Git stuff. But I wanted to share this:

[Marker.blend.zip](https://github.com/theepicsnail/Marker/files/1620789/Marker.blend.zip)

It's the marker with smooth normals 🤓 .

**Comment by hakanai** [comment]
Nice. (I just pulled this file into my fork and hope to get time to do some checks later today)

**Comment by hakanai** [comment]
Worked well for me, drop-in replacement. Usual having to scale everything down by 100 times to make it the right size for a human to hold, but oh well, that's like literally every model I've ever found anywhere. :)

**Comment by theepicsnail** [comment]
Pulled this in, it's now part of the unitypackage/repo. Thanks!
