### ISSUE TITLE
Marker impacts Avatar Performance score

### ISSUE THREAD

**Issue by Casuallynoted** [theepicsnail/Marker#4]
I’m not sure if there’s too too much that can be done about this due to the way the marker works, but it seems that having the marker on an avatar is an instant poor avatar score in VRC’s new performance indication system.

**Comment by Casuallynoted** [comment]
Update: This method has been suggested as an easy fix- perhaps it can be implemented into the main prefab?

https://amp.reddit.com/r/VRchat/comments/a9brs0/tutorial_fix_for_snail_marker_bounds_issue_very/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theepicsnail** [comment]
Neat!
I've been somewhat meaning to sort of look into better ways of doing this in general. It should be able to be done within the bounding box in general.

But at very very least, i'll post that link on the readme now just so there's some direction in the meantime.

**Comment by theepicsnail** [comment]
They've since updated the score to not be impacted, aaand apparently since unity 2018 there's been a better way to do this that doesn't impact performance rating at all!
