### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by darkrazor1** [theepicsnail/Marker#7]
![d](https://user-images.githubusercontent.com/70926332/92424431-aeb36600-f1c7-11ea-8891-d663953292cf.png)
 In picture above im getting this error when put marker on my avatars finger and trying follow your guides steps

**Comment by chibiskuld** [comment]
My first guess of what's happening here is you used Marker3.0 for SDK2. What SDK are you using? Was the project in good standing before adding the marker? Can you please also show us what appears in the console?

This will happen when the script fails to compile. If that happened, then it's most likely a problem with the project in some way.

**Comment by darkrazor1** [comment]
Where would be able find sdk Im using? One thing did find out is marker 2.0 script does work. Also my project was working well with no trouble before try marker. I also did test by making new project and just adding 3.0 marker to it and same error. The picture below is only warning I get when add the marker.
![ff](https://user-images.githubusercontent.com/70926332/92541459-6bb9c700-f289-11ea-9871-d808de5b418f.png)

**Comment by theepicsnail** [comment]
If the 2.0 marker is working, then you're using VRCSDK2 not 3. You should use the 2.0 marker for that sdk. Which is sounds like you've already figured out! 

The warning about the custom UI is fine, I can definitely clean that up, but for your project that's perfectly okay to see. It doesn't effect your avatar or anything.  

If the errors are saying things like:
> The type or namespace name 'VRC' could not be found (are you missing a using directive or an assembly reference?)

Then you're missing the VRCSDK entirely.

I suspect you'll see errors like this:
> The type or namespace name 'Avatars' does not exist in the namespace 'VRC.SDK3' (are you missing an assembly reference?)

Which just means that you're using the sdk3 marker in an sdk2 project. 

If you can reproduce the original errors, it would be helpful to click "clear" in the console tab, then take a screenshot of whatever errors remain. That would definitely help sort out what the source of the error is.

**Comment by darkrazor1** [comment]
Thank you I figure it all out I was using vrsdk2
