### ISSUE TITLE
Toggle draw delay on index controllers

### ISSUE THREAD

**Issue by Frosty704** [theepicsnail/Marker#8]
Using the SDK3 marker, whenever I gesture to start drawing, it takes the marker a second to realize that I'm doing the gesture and begin drawing. is there anyway to fix this? it gets annoying when you want to start on a new letter

**Comment by chibiskuld** [comment]
it takes .1 seconds in fact. This is was intentional, however I lessened the time in 3.1.1 as people did not like this.
